radarlegislativo/api/urls.py
# -*- coding: utf-8 -*-
# This file is part of Radar Legislativo
# Copyright © 2016 codingrights
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url
from api.views import novo_projeto


urlpatterns = [
    url('^projeto/$', novo_projeto, name="projeto-novo")
]

radarlegislativo/radarlegislativo/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from website.views import GrafoJson, TramitacoesFeed


urlpatterns = [
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^busca/', include('haystack.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^grafo.json', GrafoJson.as_view(), name='grafo-json'),
    url(r'^feed/todos.xml', TramitacoesFeed(), name='feed-todos'),
    url(r'^', include('website.urls', namespace='website')),
    url(r'^api/', include('api.urls', namespace='api')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ] + urlpatterns

radarlegislativo/website/urls.py
# -*- coding: utf-8 -*-
# This file is part of Radar Legislativo
# Copyright © 2016 codingrights
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url
from website.views import (Principal, DetalheProjeto, Agenda,
                           NovosPLs, Tramitabot, CenarioLegislativo, CustomCSS,
                           Sobre, redirect_to_graphcommons)

urlpatterns = [
    url('^$', Principal.as_view(), name="principal"),
    url('^agenda/$', Agenda.as_view(), name="agenda"),
    url('^novos-pls/$', NovosPLs.as_view(), name="novos_pls"),
    url('^cenario-legislativo/$', CenarioLegislativo.as_view(),
        name="cenario_legislativo"),
    url('^grafo/$', redirect_to_graphcommons, name="grafo"),
    url('^sobre/$', Sobre.as_view(), name="sobre"),
    url('^tramitabot/$', Tramitabot.as_view(), name="tramitabot"),
    url('^projeto/(?P<pk>\d+)/$', DetalheProjeto.as_view(), name="projeto"),
    url('^custom.css$', CustomCSS.as_view(), name="custom-css"),
]

radarlegislativo/main/models.py
#-*- coding: utf-8 -*-
# This file is part of Radar Legislativo
# Copyright © 2016 codingrights
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import unicode_literals
import datetime
import os

from django.core.exceptions import ValidationError
from django.db import models
from django.dispatch import receiver
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.utils.text import slugify

from markdownx.models import MarkdownxField

URL_API_SENADO_MATERIA = u'http://legis.senado.leg.br/dadosabertos/materia/{}'
URL_API_SENADO_MOVIMENTACOES = u'http://legis.senado.leg.br/dadosabertos/materia/movimentacoes/{}'
URL_WEB_SENADO = u'http://www25.senado.leg.br/web/atividade/materias/-/materia/{}'

URL_API_CAMARA = u'https://www.camara.leg.br/SitCamaraWS/Proposicoes.asmx?WSDL'
URL_API_CAMARA_LOCATION = u'https://www.camara.leg.br/SitCamaraWS/Proposicoes.asmx'
URL_WEB_CAMARA = u'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao={}'


@python_2_unicode_compatible
class Tag(models.Model):
    """Tags são categorias mais amplas do que palavras-chave, utilizadas para
    organizar e filtrar os projetos de lei na interface"""
    nome = models.CharField('tag', max_length=256)
    slug = models.SlugField(max_length=20, unique=True)
    icon = models.FileField(upload_to='tags-icons', null=True, blank=True)

    def __str__(self):
        return self.nome


@python_2_unicode_compatible
class PalavraChave(models.Model):
    """Palavras-chave são mais granulares do que as tags, normalmente vem como
    parâmetro quando adiciona-se um projeto de lei automaticamente (por
    exemplo, com o Raspador Legislativo). Armazena-se as palavras-chave para
    fins de busca, de mapear o porquê de um projeto ter sido adicionado e para
    podermos relacionar documentos a diversos projetos de lei de forma mais
    granular do que via tags."""
    nome = models.CharField('palavra-chave', max_length=256, unique=True)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'palavra-chave'
        verbose_name_plural = 'palavras-chave'
        ordering = ('nome',)


class ProjetoManager(models.Manager):

    def na_mesma_semana_que_o_dia(self, dia):
        semana = dia.isocalendar()[1]
        return self.filter(cadastro__week=semana)

    def mais_novo(self):
        return self.order_by('-cadastro').first()

    def novos(self):
        return self.na_mesma_semana_que_o_dia(self.mais_novo().cadastro)


class ProjetosPublicadosManager(ProjetoManager):

    def get_queryset(self):
        qs = super(ProjetosPublicadosManager, self).get_queryset()
        return qs.filter(publicado=True)


class ProjetosNaoPublicadosManager(ProjetoManager):

    def get_queryset(self):
        qs = super(ProjetosNaoPublicadosManager, self).get_queryset()
        return qs.filter(publicado=False)


class ProjetosPublicadosManager(ProjetoManager):

    def get_queryset(self):
        qs = super(ProjetosPublicadosManager, self).get_queryset()
        return qs.filter(publicado=True)


class ProjetosNaoPublicadosManager(ProjetoManager):

    def get_queryset(self):
        qs = super(ProjetosNaoPublicadosManager, self).get_queryset()
        return qs.filter(publicado=False)


@python_2_unicode_compatible
class Projeto(models.Model):

    objects = ProjetoManager()
    publicados = ProjetosPublicadosManager()
    nao_publicados = ProjetosNaoPublicadosManager()

    CAMARA = "CA"
    SENADO = "SE"

    ORIGEM_CHOICES = (
        (CAMARA, "Câmara"),
        (SENADO, "Senado"),
    )

    VERDE = 1
    AMARELO = 2
    VERMELHO = 3

    IMPACTO_CHOICES = (
        (VERDE, '🙂️'),
        (AMARELO, "😐"),
        (VERMELHO, "🙁")
    )

    origem = models.CharField(max_length=2, choices=ORIGEM_CHOICES)
    id_site = models.IntegerField('id no site de origem')
    nome = models.CharField(max_length=255)
    tags = models.ManyToManyField(Tag)
    palavras_chave = models.ManyToManyField(PalavraChave, blank=True)

    apresentacao = models.DateField()
    ementa = models.TextField()
    autoria = models.CharField(max_length=255)
    apensadas = models.TextField(blank=True)
    local = models.TextField(blank=True)

    html_original = models.TextField(blank=True)

    apelido = models.CharField(max_length=255, blank=True)
    importante = models.BooleanField(default=False)
    urgente = models.BooleanField(default=False)
    arquivado = models.BooleanField(default=False)
    promulgado = models.BooleanField(default=False)
    impacto = models.IntegerField(choices=IMPACTO_CHOICES, default=AMARELO)
    informacoes_adicionais = MarkdownxField(blank=True)
    clippings = MarkdownxField(blank=True)
    pontos_principais = MarkdownxField(blank=True)
    texto_acao = models.TextField(blank=True)
    publicado = models.BooleanField(db_index=True, default=True)

    nome_da_lei_promulgada = models.CharField(max_length=255, blank=True,
            help_text="Nome da lei caso o projeto tenha sido promulgado")
    link_da_lei_promulgada = models.TextField(blank=True,
            help_text="Link para o texto da lei caso o projeto tenha "
            "sido promulgado")

    publicado = models.BooleanField(db_index=True, default=True)

    cadastro = models.DateField(auto_now_add=True)

    ultima_atualizacao = models.DateField(default=datetime.date.today)

    texto_acao.verbose_name = "texto de ação"

    class Meta:
        unique_together = (("origem", "id_site"),)
        ordering = ['-ultima_atualizacao']

    def tag_list(self):
        """
        Shows a list of tags for this project.

        We use this for the list_display in ProjetoAdmin, but it adds another
        (potentially big) query to that page. If it grows too slow, we can
        remove this (and not have a list of tags in the admin list_display).
        """
        return ', '.join(self.tags.values_list('nome',
            flat=True).order_by('nome'))

    @property
    def ultima_tramitacao(self):
        return self.tramitacao_set.latest()

    @property
    def ultimas_tramitacoes(self):
        return self.tramitacao_set.order_by('-data')

    @property
    def slug(self):
        return slugify(self.nome)

    @property
    def situacao(self):
        return "{} - {}".format(self.ultima_tramitacao.local, self.ultima_tramitacao.descricao)

    @property
    def link(self):
        if self.origem == self.SENADO:
            return URL_WEB_SENADO.format(self.id_site)
        elif self.origem == self.CAMARA:
            return URL_WEB_CAMARA.format(self.id_site)

    @property
    def documentos(self):
        if hasattr(self, '_documentos'):
            return self._documentos

        self._documentos = Documento.objects.filter(
            models.Q(tags__in=self.tags.all()) |
            models.Q(palavras_chave__in=self.palavras_chave.all()) |
            models.Q(projetos=self)
        )
        return self._documentos

    def link_para_edicao(self):
        url_name =  "admin:{}_{}_change".format(self._meta.app_label, self._meta.model_name)
        return reverse(url_name, args=(self.id,))

    def get_absolute_url(self):
        return reverse("website:projeto", args=[self.pk])

    def __str__(self):
        return '{} - {}'.format(self.nome, self.get_origem_display())


@python_2_unicode_compatible
class Tramitacao(models.Model):
    id_site = models.CharField(max_length=255)
    data = models.DateField()
    projeto = models.ForeignKey(Projeto)
    local = models.CharField(max_length=255)
    descricao = models.TextField()

    class Meta:
        ordering = ["-data"]
        get_latest_by = "data"
        verbose_name_plural = "tramitações"

    def save(self, *args, **kwargs):
        result = super(Tramitacao, self).save(*args, **kwargs)
        self.projeto.ultima_atualizacao = self.data
        self.projeto.save()
        return result

    def get_absolute_url(self):
        return self.projeto.get_absolute_url()

    @property
    def descricao_limpa(self):
        string_to_remove = 'Inteiro teor'
        if self.descricao.endswith(string_to_remove):
            return self.descricao[:-len(string_to_remove)]
        return self.descricao

    def __str__(self):
        return u'{} - {} - {}'.format(self.projeto, self.data, self.local)


@python_2_unicode_compatible
class Documento(models.Model):
    titulo = models.CharField('Título', max_length=255)
    projetos = models.ManyToManyField(Projeto, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    palavras_chave = models.ManyToManyField(PalavraChave, blank=True)
    criado_em = models.DateTimeField(auto_now_add=True, db_index=True)
    arquivo = models.FileField(upload_to='documentos', blank=True, null=True)
    url = models.URLField('URL', blank=True, null=True)

    # Forca um Documento a ter arquivo ou URL
    def clean(self):
        if not self.arquivo and not self.url:
            raise ValidationError(
            'Um documento deve ter Arquivo ou URL. Preencha um dos dois campos.'
            )
        if self.arquivo and self.url:
            raise ValidationError(
            'Um documento deve ter Arquivo ou URL. Apague um dos campos.'
            )

    def get_url(self):
        return self.url if self.url else self.arquivo.url

    def __str__(self):

radarlegislativo/website/forms.py
#  -*- coding: utf-8 -*-
# This file is part of Radar Legislativo
# Copyright © 2017 codingrights
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import datetime
from django import forms

from main.models import Projeto, Tag
from parlamento.models import ComissaoCamara, ComissaoSenado


ORIGEM_DEFAULT = "Todas"


def get_comissoes():
    return (
        ("", "Todas"),
        ("Senado", tuple(
            ComissaoSenado.objects.all().values_list('id', 'nome')),
        ),
        ("Câmara", tuple(
            ComissaoCamara.objects.all().values_list('id', 'nome')),
        ),
    )


def get_tags():
    return ((tag.id, tag.nome) for tag in Tag.objects.all())


class CustomCheckboxSelectMultiple(forms.CheckboxSelectMultiple):
    template_name = "website/checkbox_select_multiple.html"


class FilterForm(forms.Form):
    categoria = forms.TypedMultipleChoiceField(
        required=False,
        widget=CustomCheckboxSelectMultiple(
            attrs={"class": "submit-on-change"}
        ),
        choices=get_tags,
        coerce=int,
    )
    comissao = forms.TypedChoiceField(
        required=False,
        empty_value=None,
        choices=get_comissoes,
        widget=forms.Select(
            attrs={"class": "form-control submit-on-change"}
        ),
        coerce=int,
    )
    origem = forms.MultipleChoiceField(
        required=False,
        widget=CustomCheckboxSelectMultiple(
            attrs={"class": "submit-on-change"}
        ),
        choices=Projeto.ORIGEM_CHOICES,
    )
    impacto = forms.MultipleChoiceField(
        required=False,
        widget=CustomCheckboxSelectMultiple(
            attrs={"class": "submit-on-change"}
        ),
        choices=Projeto.IMPACTO_CHOICES,
    )

    q = forms.CharField(
        required=False,
        max_length=255,
        widget=forms.TextInput(
            attrs={
                "class": "form-control sumbit-on-enter",
                "placeholder": u"buscar",
            }
        ),
    )

    ordem = forms.ChoiceField(
        required=False,
        widget=forms.Select(
            attrs={"class": "form-control submit-on-change"}
        ),
        choices=(
            ("", "ordenar por últimas tramitações"),
            ("novos", "ordenar por mais recentes"),
            ("urgentes", "destacar urgentes"),
            ("promulgados", "destacar promulgados"),
            ("arquivados", "destacar arquivados"),
        )
    )


class FormListagemSemanal(forms.Form):
    origem_default = ORIGEM_DEFAULT
    data = forms.DateField(
        required=True,
        widget=forms.DateInput(
            attrs={
                "class": "form-control text-center submit-on-change",
                "id": "datepicker",
            },
            format="%d/%m/%Y",
        ),
        initial=datetime.date.today,
    )
    origem = forms.ChoiceField(
        required=False,
        widget=forms.Select(
            attrs={"class": "form-control text-center submit-on-change"}
        ),
        choices=(("", ORIGEM_DEFAULT),) + Projeto.ORIGEM_CHOICES
    )

radarlegislativo/agenda/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

radarlegislativo/tramitabot/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

radarlegislativo/website/templates/website/base.html
{% load static %}
{% load website_tags %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ short_title }}{% block titulo_extra %}{% endblock %}</title>
  {% if custom_favicon %}<link rel="shortcut icon" type="image/png" href="{{ custom_favicon }}">{% endif %}
  {% if highlight_font_url %}<link href="{{ highlight_font_url }}" rel="stylesheet">{% endif %}
  <link rel="stylesheet" href="{% static 'styles/radar.css' %}">
  <link rel="stylesheet" href="{% url 'website:custom-css' %}">
  {% block extra_head %}{% endblock %}
</head>

<body {% block body_class %}{% endblock %}>
  {% block alerta %}{% endblock %}
  {% block menu_principal %}
  <!-- MENU PRINCIPAL -->
  <nav id="main_navbar" class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Abrir/fechar menu</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'website:principal' %}">
          <img src="{{ small_logo }}" alt="{{ short_title }}" />
          {{ short_title }}
        </a>
      </div>

      <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'website:principal' %}">Projetos de lei</a></li>
          <li><a href="{% url 'website:agenda' %}">Agenda da semana</a></li>
          <li><a href="{% url 'website:novos_pls' %}">Novos PLs</a></li>
        {% if tramitabot %}
          <li><a href="{% url 'website:tramitabot' %}">Tramitabot</a></li>
        {% endif %}
          <li><a href="{% url 'website:cenario_legislativo' %}">Entenda o legislativo</a></li>
        {% if graph_url %}
          <li><a href="{{ graph_url }}">Grafo de PLS</a></li>
        {% endif %}
          <li><a href="{% url 'website:sobre' %}">Sobre</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- MENU PRINCIPAL -->
  {% endblock %}

  {% block header %}
  <!-- HEADER -->
  <div class="main-page-header container-fluid text-center">
    <h1>{{ long_title }}</h1>
    <p>{{ headline }}</p>
    <img class="robo" src="{{ large_logo }}" alt="{{ long_title }}" />
  </div>
  <!-- HEADER -->
  {% endblock %}

  {% block conteudo %}

  {% endblock conteudo %}

  {% block rodape %}
  <!-- RODAPE -->
  <div class="rodape container-fluid">
    <div class="navegacao container">
      <div class="col-sm-4">
        <h6>{{ footer_headline }}</h6>
        <ul class="nav">
          <li><a href="{% url 'website:agenda' %}">agenda da semana</a></li>
          <li><a href="{% url 'website:principal' %}">projetos de lei</a></li>
          <li><a href="{% url 'website:novos_pls' %}">novos PLs</a></li>
          <li><a href="{% url 'website:cenario_legislativo' %}">cenário legislativo</a></li>
          {% if graph_url %}<li><a href="{{ graph_url }}">grafo de pls</a></li>{% endif %}
          {% if tramitabot %}<li><a href="{% url 'website:tramitabot' %}">tramitabot</a></li>{% endif %}
          <li><a href="{% url 'website:sobre' %}">sobre</a></li>
        </ul>
      </div>
      <div class="col-sm-4">
        <h6>categorias</h6>
        <ul class="nav">
          {% get_cached_tags as tags %}
          {% for tag in tags %}
          <li><a href="{% link_filtro tag.slug %}">{{ tag.nome.lower }}</a></li>
          {% endfor %}
        </ul>
      </div>
      <div class="col-sm-4">
        <h6>{{ maintained_by_name }}</h6>
        <p><a href="https://twitter.com/{{ maintained_by_twiiter }}">@{{ maintained_by_twiiter }}</a></p>
        <p><a href="{{ maintained_by_extra_url }}">{{ maintained_by_extra_text }}</a></p>
        <a href="{{ maintained_by_url }}"><img src="{{ maintained_by_logo }}" alt="{{ maintained_by_name }} logo" /></a>
      </div>
    </div>

    <div class="licenca row">
      <p>Este projeto foi criado pela <a href="https://www.codingrights.org/">Coding Rights</a> e está licenciado com uma Licença Creative Commons 4.0 CompartilhaIgual.</p>
      <p>Código aberto disponível no <a href="https://gitlab.com/codingrights"><img class="logo" src="{% static 'img/logo-gitlab.svg' %}" alt="" /> Gitlab</a></p>
    </div>
  </div>
  <!-- RODAPE -->
  {% endblock %}

  <!-- SCRIPTS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
  {% if tracking_code %}{{ tracking_code }}{% endif %}
  {% block scripts_extra %}
  {% endblock %}
  <!-- SCRIPTS -->
</body>
</html>

radarlegislativo/website/templates/website/novos_pls.html
{% extends "website/base.html" %}
{% load static %}
{% load website_tags %}

{% block extra_title %}| Novos PLs{% endblock %}

{% block body_class %}class="pagina-novos-pls"{% endblock %}

{% block extra_head %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
{% endblock %}

{% block header %}
  <!-- HEADER -->
  <div class="main-page-header container-fluid text-center">
    <h1>Novos PLs</h1>
    <p>Acompanhamento semanal de novos projetos de lei</p>
    <img class="robo" src="{{ large_logo }}" alt="{{ long_title }}" />
  </div>
  <!-- HEADER -->
{% endblock %}

{% block conteudo %}
  <div class="filtros-novos-pls container-fluid text-center">
    <form id="filtros" method="get">
      {{ form.origem }}
      {{ form.data }}
    </form>
  </div>

  <div class="datas-novos-pls container-fluid text-center">
    <div class="row table-row-sm item-divider">
    {% for inicio, fim in semanas_proximas %}
      {% if forloop.first %}
        <div class="col-sm-1">
          <a href="{% change_url_parameter request 'data' inicio|date:'d/m/Y' %}">
            <span class="navegacao glyphicon glyphicon-menu-left" aria-hidden="true"></span>
          </a>
        </div>
      {% elif forloop.last %}
        <div class="col-sm-1">
          <a href="{% change_url_parameter request 'data' inicio|date:'d/m/Y' %}">
            <span class="navegacao glyphicon glyphicon-menu-right" aria-hidden="true"></span>
          </a>
	</div>
      {% else %}
        <div class="col-sm-2{% if inicio in dias_da_semana %} active{% endif %}">
          <a href="{% change_url_parameter request 'data' inicio|date:'d/m/Y' %}">
            <p class="novos-pls-data-mes">{{ inicio|date:"d/m" }} - {{ fim|date:"d/m" }}</p>
            {% if inicio == inicio_da_semana_atual %}
              <p class="novos-pls-data-hoje">esta semana</p>
            {% endif %}
          </a>
        </div>
      {% endif %}
    {% endfor %}
    </div>
  </div>

  <div class="conteudo-principal">
    <div class="container">
      <div class="row">
	  {% for projeto in novos_pls %}

	  {% ifchanged projeto.cadastro %}
	    {% if not forloop.first %}<div class="divider-horizontal"></div>{% endif %}
	    <h2 class="col-md-8 col-md-offset-2 novos-pls-data-projeto">{{ projeto.cadastro|date:"d.m (l)" }}</h2>
	  {% endifchanged %}

          <div class="col-md-8 col-md-offset-2 novos-pls_item">

            <div class="pull-right pls-icones">
	      {% for tag in projeto.tags.all %}
	        {% get_icon_html_from_tag_id tag.id %}
	      {% endfor %}
	      {% if projeto.get_impacto_display == '🙂️' %}
                <img src="{% static 'img/icons/face-happy-icon.svg' %}" data-toggle="tooltip" title="Bom" />
	      {% elif projeto.get_impacto_display == '😐' %}
                <img src="{% static 'img/icons/face-medium-icon.svg' %}" data-toggle="tooltip" title="Atenção: pode ameaçar direitos" />
	      {% elif projeto.get_impacto_display == '🙁' %}
                <img src="{% static 'img/icons/face-unhappy-icon.svg' %}" data-toggle="tooltip" title="Ruim" />
	      {% endif %}
	      {% if projeto.urgente %}
                <img src="{% static 'img/icons/lightningicon.svg' %}" data-toggle="tooltip" title="Urgente" />
	      {% endif %}
	      {% if projeto.arquivado %}
	        <img src="{% static 'img/icons/archiveicon.svg' %}" data-toggle="tooltip" title="Arquivado" />
	      {% endif %}
	      {% if projeto.promulgado %}
	        <img src="{% static 'img/icons/promulgatedicon.svg' %}" data-toggle="tooltip" title="Promulgado" />
	      {% endif %}
	    </div>

            <h2 class="novos-pls-nome-projeto col-lg-6">{{ projeto.nome }}</h2>

	    <table class="novos-pls-detalhes-projeto">
	      <tr class="novos-pls-titulos-projeto">
	        <th>Apresentação</th>
	        <th>Autoria</th>
	        <th>Origem</th>
	        <th>Situacao</th>
	      </tr>
	      <tr class="novos-pls-descricao-projeto">
	        <td>{{ projeto.apresentacao }}</td>
	        <td>{{ projeto.autoria }}</td>
	        <td> {{ projeto.origem }}</td>
	        <td>{{ projeto.situacao }}</td>
	      </tr>
	    </table>

	    <h3 class="novos-pls-titulo-detalhe">Ementa</h3>
            <p class="novos-pls-descricao-detalhe">{{ projeto.ementa }}</p>

	    <h3 class="novos-pls-titulo-detalhe">Pontos principais</h3>
	    {{ projeto.pontos_principais|safe|markdown_text }}

	    <a class="btn btn-primary" href="{{ projeto.get_absolute_url }}">ver mais</a>
	  </div>

	{% empty %}
	  <p>Não existem projetos novos na semana selecionada.</p>
	{% endfor %}
      </div>
    </div>
  </div>

  <div class="divider-horizontal"></div>
{% endblock %}
{% block scripts_extra %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  <script src="{% static 'js/forms.js' %}"></script>
  <script src="{% static 'js/datepicker-pt-BR.js' %}"></script>
  <script type="text/javascript">
    $(function() {
      $("#datepicker").datepicker({
        beforeShowDay: function(date){
          var day = date.getDay();
          return [day >= 1 && day <= 5, ""];
        }
      });
    });
  </script>
{% endblock %}